apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-go
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: go
        image: marcelo27062010/imagem-go
        ports:
        - containerPort: 8000

       


      
    
  
  