steps:

- id: 'Instalando o app ci_challenge'
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'ci_challenge']
  env: ['GOPATH=.']

- id: 'Executando Teste Unitário'
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v','./...']
  env: ['GOPATH=.']

- id: 'Fazendo o Push da Imagem Para O Cloud Registry'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/ci_challenge_go:latest'
    - '.'

images: ['gcr.io/$PROJECT_ID/ci_challenge_go:latest']